ALTER TABLE event_volunteers
  ADD COLUMN meal_choice VARCHAR(100) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS dinner_meal_options (
  id INT AUTO_INCREMENT PRIMARY KEY,
  option_name VARCHAR(100) NOT NULL,
  sort_order INT NOT NULL DEFAULT 999,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
